### ISSUE TITLE
Spot-checks for testing

### ISSUE THREAD

**Issue by patrickmj** [omeka/Omeka#576]
@sheilabrennan This is a list of issues that create relatively small changes to the interface -- very low-worry level, but here just in case a spot check is in order. NB -- not all the issues are closed yet. \* indicates issues that are closed
- [ ] #258 Check the "Get support" links added to theme and plugin browse *
- [ ] #555 Check media file display in admin/files/show *
- [ ] #542 Check plain text links in files/show *
- [ ] #568 Check filter by record type in admin/tags *
- [ ] #519 Check many plugins adding to admin sidebar don't disappear *
- [ ] #59 Check the searches in admin/users *
